# Generated by Django 4.2.2 on 2023-06-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_productimagemodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='image'),
        ),
    ]
